# Generated by Django 2.0 on 2018-04-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pfdb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('platfrom_name', models.CharField(blank=True, max_length=64, verbose_name='平台名称')),
                ('platfrom_url', models.URLField(blank=True, max_length=128, verbose_name='平台地址')),
            ],
            options={
                'verbose_name': '平台管理',
                'verbose_name_plural': '平台管理',
                'db_table': 'pfdb',
            },
        ),
    ]
