# Generated by Django 2.0 on 2018-05-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
                model_name='assets',
                name='addr',
                field=models.CharField(blank=True, default='库房', max_length=24, null=True, verbose_name='存放地点'),
        ),
        migrations.AddField(
                model_name='assets',
                name='nmac',
                field=models.CharField(blank=True, max_length=24, null=True, verbose_name='有线mac'),
        ),
        migrations.AddField(
                model_name='assets',
                name='pid',
                field=models.CharField(blank=True, max_length=24, null=True, verbose_name='设备号'),
        ),
        migrations.AddField(
                model_name='assets',
                name='ps',
                field=models.CharField(blank=True, max_length=24, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
                model_name='assets',
                name='sn',
                field=models.CharField(blank=True, max_length=24, null=True, verbose_name='SN号'),
        ),
        migrations.AddField(
                model_name='assets',
                name='wmac',
                field=models.CharField(blank=True, max_length=24, null=True, verbose_name='无线mac'),
        ),
        migrations.AlterField(
                model_name='assets',
                name='gtime',
                field=models.DateField(blank=True, null=True, verbose_name='归还(报废)时间'),
        ),
    ]
