# Generated by Django 2.0 on 2018-06-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20180530_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='uconf',
        ),
        migrations.AddField(
            model_name='assets',
            name='cpu',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='CPU'),
        ),
        migrations.AddField(
            model_name='assets',
            name='disk',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='硬盘'),
        ),
        migrations.AddField(
            model_name='assets',
            name='mem',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='内存'),
        ),
        migrations.AddField(
            model_name='assets',
            name='upart',
            field=models.CharField(blank=True, db_index=True, max_length=24, null=True, verbose_name='部门'),
        ),
    ]
