# Generated by Django 2.0 on 2018-04-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cmdb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('hostname', models.CharField(max_length=64, unique=True, verbose_name='主机名')),
                ('network_ip', models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='外网IP')),
                ('inner_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='内网IP')),
                ('system', models.CharField(blank=True, max_length=128, null=True, verbose_name='系统版本')),
                ('cpu', models.CharField(blank=True, max_length=64, null=True, verbose_name='CPU')),
                ('memory', models.CharField(blank=True, max_length=64, null=True, verbose_name='内存')),
                ('disk', models.CharField(blank=True, max_length=256, null=True, verbose_name='硬盘')),
                ('platform', models.CharField(choices=[('虚拟机', '虚拟机'), ('物理机', '物理机'), ('其他', '其他')], max_length=128, verbose_name='机器类型')),
                ('platform_size', models.CharField(blank=True, max_length=128, null=True, verbose_name='机器型号')),
                ('region', models.CharField(choices=[('香港', '香港'), ('上海', '上海')], max_length=128, verbose_name='机柜名')),
                ('manager', models.CharField(choices=[('admin', 'admin'), ('其他', '其他')], max_length=128, verbose_name='负责人')),
                ('use', models.CharField(choices=[('admin', 'admin'), ('其他', '其他')], max_length=128, verbose_name='使用人')),
                ('project', models.CharField(choices=[('项目1', '项目1'), ('项目2', '项目2'), ('项目3', '项目3'), ('其他', '其他')], max_length=128, verbose_name='项目')),
                ('Instance_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='实例ID')),
                ('ps', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注（用途）')),
                ('port', models.IntegerField(blank=True, default='22', null=True, verbose_name='登录端口')),
                ('ctime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='申请时间')),
                ('utime', models.DateTimeField(auto_now=True, null=True, verbose_name='到期时间')),
            ],
            options={
                'verbose_name': '资产管理',
                'verbose_name_plural': '资产管理',
                'db_table': 'cmdb',
                'permissions': {('read_asset', '只读资产管理')},
            },
        ),
    ]
