# Generated by Django 2.0 on 2018-04-18 06:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cmdb',
            options={'permissions': {('read_cmdb', '只读资产管理')}, 'verbose_name': '资产管理', 'verbose_name_plural': '资产管理'},
        ),
        migrations.RemoveField(
            model_name='cmdb',
            name='Instance_id',
        ),
        migrations.RemoveField(
            model_name='cmdb',
            name='port',
        ),
        migrations.AddField(
            model_name='cmdb',
            name='PID',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='序列号'),
        ),
        migrations.AddField(
            model_name='cmdb',
            name='UID',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='资产编号'),
        ),
        migrations.AddField(
            model_name='cmdb',
            name='gtime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上架时间'),
        ),
        migrations.AddField(
            model_name='cmdb',
            name='logintype',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='登录方式'),
        ),
        migrations.AddField(
            model_name='cmdb',
            name='netinfo',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='网卡'),
        ),
        migrations.AddField(
            model_name='cmdb',
            name='otime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='下架时间'),
        ),
        migrations.AddField(
            model_name='cmdb',
            name='power',
            field=models.CharField(choices=[('是', '是'), ('否', '否')], default=django.utils.timezone.now, max_length=128, verbose_name='电源冗余'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cmdb',
            name='ctime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='申请时间'),
        ),
        migrations.AlterField(
            model_name='cmdb',
            name='utime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='到期时间'),
        ),
    ]
