# Generated by Django 2.0 on 2018-04-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20180418_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmdb',
            name='ctime',
            field=models.DateField(blank=True, null=True, verbose_name='申请时间'),
        ),
        migrations.AlterField(
            model_name='cmdb',
            name='gtime',
            field=models.DateField(blank=True, null=True, verbose_name='上架时间'),
        ),
        migrations.AlterField(
            model_name='cmdb',
            name='network_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='外网IP'),
        ),
        migrations.AlterField(
            model_name='cmdb',
            name='otime',
            field=models.DateField(blank=True, null=True, verbose_name='下架时间'),
        ),
        migrations.AlterField(
            model_name='cmdb',
            name='utime',
            field=models.DateField(blank=True, null=True, verbose_name='到期时间'),
        ),
    ]
