# Generated by Django 2.0 on 2018-04-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20180420_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmdb',
            name='ctime',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='申请时间'),
        ),
        migrations.AlterField(
            model_name='cmdb',
            name='gtime',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='上架时间'),
        ),
        migrations.AlterField(
            model_name='cmdb',
            name='otime',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='下架时间'),
        ),
        migrations.AlterField(
            model_name='cmdb',
            name='utime',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='到期时间'),
        ),
    ]
