# Generated by Django 2.0 on 2018-04-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20180420_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmdb',
            name='use',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='使用人'),
        ),
    ]
