# Generated by Django 2.0 on 2018-06-08 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform_asstes',
            name='platform_size',
        ),
        migrations.AlterField(
            model_name='platform_size',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_info.platform', verbose_name='设备类型'),
        ),
        migrations.DeleteModel(
            name='platform_asstes',
        ),
    ]
