# Generated by Django 2.0 on 2018-05-09 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform_size',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_info.platform', verbose_name='设备型号'),
        ),
    ]
