# Generated by Django 2.0 on 2018-05-23 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
                name='tb_log',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('log_info', models.TextField(verbose_name='操作记录')),
                    ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.assets',
                                              verbose_name='资产编号')),
                ],
        ),
    ]
