# Generated by Django 2.0 on 2018-06-06 10:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb_log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_log',
            name='user',
            field=models.CharField(default=django.utils.timezone.now, max_length=24, verbose_name='操作人'),
            preserve_default=False,
        ),
    ]
