# Generated by Django 2.0 on 2018-07-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=64, verbose_name='事件名称')),
                ('event_ps', models.CharField(max_length=128, verbose_name='事件描述')),
                ('person', models.CharField(max_length=14, verbose_name='处理人')),
                ('event_starttime', models.DateField(verbose_name='时间开始时间')),
                ('event_endtime', models.DateField(verbose_name='计划完成时间')),
                ('event_status', models.CharField(choices=[('待处理', '待处理'), ('已完成', '已完成')], max_length=24, verbose_name='时间状态')),
            ],
            options={
                'verbose_name': '工作日志',
                'verbose_name_plural': '工作日志',
                'db_table': 'order',
            },
        ),
    ]
