# Generated by Django 2.0 on 2018-07-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='event_starttime',
            field=models.DateField(auto_now_add=True, verbose_name='事件创建时间'),
        ),
    ]
