# Generated by Django 2.0 on 2018-08-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0003_order_event_updatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='event_ps',
            field=models.CharField(max_length=4000, verbose_name='事件描述'),
        ),
    ]
