# Generated by Django 2.0 on 2018-05-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gzdb',
            fields=[
                ('type', models.CharField(max_length=28, unique=True, verbose_name='设备类型')),
                ('type_size', models.CharField(max_length=28, verbose_name='设备型号')),
                ('id', models.CharField(blank=True, max_length=28, primary_key=True, serialize=False, verbose_name='资产编号')),
                ('uid', models.CharField(blank=True, max_length=28, null=True, verbose_name='设备编号')),
                ('sn', models.CharField(blank=True, max_length=28, null=True, verbose_name='序列号')),
                ('stat', models.CharField(blank=True, max_length=28, null=True, verbose_name='状态')),
                ('depart', models.CharField(blank=True, max_length=28, null=True, verbose_name='部门')),
                ('addr', models.CharField(blank=True, max_length=28, null=True, verbose_name='设备地址')),
                ('user', models.CharField(blank=True, max_length=28, null=True, verbose_name='使用人')),
                ('ps', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注（配置和用途）')),
                ('history', models.CharField(blank=True, max_length=1024, null=True, verbose_name='历史记录')),
            ],
            options={
                'verbose_name': '固定资产管理',
                'verbose_name_plural': '固定资产管理',
                'db_table': 'gzdb',
                'permissions': {('read_gzdb', '只读资产管理')},
            },
        ),
    ]
